cargo-features = ["edition2021"]

[package]
name = "kernel"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>", "Justus K <justus.k@protonmail.com>"]
license = "GPL-2.0"
repository = "https://github.com/vbe0201/Saturnus"
edition = "2021"

[dependencies]
